from flask import Blueprint, request, jsonify
from app.services.cuisine import get_meals_by_country
from app.services.countries import get_countries
from app.services.art import get_art_by_country
from app.services.history import get_history
from app.services.traditions import get_heritage_by_country

bp = Blueprint("cultures", __name__)

@bp.route("/", methods=["GET"])
def list_cultures():
    cultures = [
        {"id": "algeria", "name": "Algeria", "continent": "Africa"},
        {"id": "angola", "name": "Angola", "continent": "Africa"},
        {"id": "benin", "name": "Benin", "continent": "Africa"},
        {"id": "botswana", "name": "Botswana", "continent": "Africa"},
        {"id": "burkina faso", "name": "Burkina Faso", "continent": "Africa"},
        {"id": "burundi", "name": "Burundi", "continent": "Africa"},
        {"id": "cabo verde", "name": "Cabo Verde", "continent": "Africa"},
        {"id": "cameroon", "name": "Cameroon", "continent": "Africa"},
        {"id": "central african republic", "name": "Central African Republic", "continent": "Africa"},
        {"id": "chad", "name": "Chad", "continent": "Africa"},
        {"id": "comoros", "name": "Comoros", "continent": "Africa"},
        {"id": "democratic republic of the congo", "name": "Democratic Republic of the Congo", "continent": "Africa"},
        {"id": "republic of the congo", "name": "Republic Of The Congo", "continent": "Africa"},
        {"id": "djibouti", "name": "Djibouti", "continent": "Africa"},
        {"id": "egypt", "name": "Egypt", "continent": "Africa"},
        {"id": "equatorial guinea", "name": "Equatorial Guinea", "continent": "Africa"},
        {"id": "eritrea", "name": "Eritrea", "continent": "Africa"},
        {"id": "eswatini", "name": "Eswatini", "continent": "Africa"},
        {"id": "ethiopia", "name": "Ethiopia", "continent": "Africa"},
        {"id": "gabon", "name": "Gabon", "continent": "Africa"},
        {"id": "gambia", "name": "Gambia", "continent": "Africa"},
        {"id": "ghana", "name": "Ghana", "continent": "Africa"},
        {"id": "guinea", "name": "Guinea", "continent": "Africa"},
        {"id": "guinea-bissau", "name": "Guinea-Bissau", "continent": "Africa"},
        {"id": "ivory coast", "name": "Ivory Coast", "continent": "Africa"},
        {"id": "kenya", "name": "Kenya", "continent": "Africa"},
        {"id": "lesotho", "name": "Lesotho", "continent": "Africa"},
        {"id": "liberia", "name": "Liberia", "continent": "Africa"},
        {"id": "libya", "name": "Libya", "continent": "Africa"},
        {"id": "madagascar", "name": "Madagascar", "continent": "Africa"},
        {"id": "malawi", "name": "Malawi", "continent": "Africa"},
        {"id": "mali", "name": "Mali", "continent": "Africa"},
        {"id": "mauritania", "name": "Mauritania", "continent": "Africa"},
        {"id": "mauritius", "name": "Mauritius", "continent": "Africa"},
        {"id": "morocco", "name": "Morocco", "continent": "Africa"},
        {"id": "mozambique", "name": "Mozambique", "continent": "Africa"},
        {"id": "namibia", "name": "Namibia", "continent": "Africa"},
        {"id": "niger", "name": "Niger", "continent": "Africa"},
        {"id": "nigeria", "name": "Nigeria", "continent": "Africa"},
        {"id": "rwanda", "name": "Rwanda", "continent": "Africa"},
        {"id": "sao tome and principe", "name": "Sao Tome and Principe", "continent": "Africa"},
        {"id": "senegal", "name": "Senegal", "continent": "Africa"},
        {"id": "seychelles", "name": "Seychelles", "continent": "Africa"},
        {"id": "sierra leone", "name": "Sierra Leone", "continent": "Africa"},
        {"id": "somalia", "name": "Somalia", "continent": "Africa"},
        {"id": "south africa", "name": "South Africa", "continent": "Africa"},
        {"id": "south sudan", "name": "South Sudan", "continent": "Africa"},
        {"id": "sudan", "name": "Sudan", "continent": "Africa"},
        {"id": "tanzania", "name": "Tanzania", "continent": "Africa"},
        {"id": "togo", "name": "Togo", "continent": "Africa"},
        {"id": "tunisia", "name": "Tunisia", "continent": "Africa"},
        {"id": "uganda", "name": "Uganda", "continent": "Africa"},
        {"id": "zambia", "name": "Zambia", "continent": "Africa"},
        {"id": "zimbabwe", "name": "Zimbabwe", "continent": "Africa"},
        {"id": "antigua and barbuda", "name": "Antigua and Barbuda", "continent": "America"},
        {"id": "argentina", "name": "Argentina", "continent": "America"},
        {"id": "bahamas", "name": "Bahamas", "continent": "America"},
        {"id": "barbados", "name": "Barbados", "continent": "America"},
        {"id": "belize", "name": "Belize", "continent": "America"},
        {"id": "bolivia", "name": "Bolivia", "continent": "America"},
        {"id": "brazil", "name": "Brazil", "continent": "America"},
        {"id": "canada", "name": "Canada", "continent": "America"},
        {"id": "chile", "name": "Chile", "continent": "America"},
        {"id": "colombia", "name": "Colombia", "continent": "America"},
        {"id": "costa rica", "name": "Costa Rica", "continent": "America"},
        {"id": "cuba", "name": "Cuba", "continent": "America"},
        {"id": "dominica", "name": "Dominica", "continent": "America"},
        {"id": "dominican republic", "name": "Dominican Republic", "continent": "America"},
        {"id": "ecuador", "name": "Ecuador", "continent": "America"},
        {"id": "el salvador", "name": "El Salvador", "continent": "America"},
        {"id": "grenada", "name": "Grenada", "continent": "America"},
        {"id": "guatemala", "name": "Guatemala", "continent": "America"},
        {"id": "guyana", "name": "Guyana", "continent": "America"},
        {"id": "haiti", "name": "Haiti", "continent": "America"},
        {"id": "honduras", "name": "Honduras", "continent": "America"},
        {"id": "jamaica", "name": "Jamaica", "continent": "America"},
        {"id": "mexico", "name": "Mexico", "continent": "America"},
        {"id": "nicaragua", "name": "Nicaragua", "continent": "America"},
        {"id": "panama", "name": "Panama", "continent": "America"},
        {"id": "paraguay", "name": "Paraguay", "continent": "America"},
        {"id": "peru", "name": "Peru", "continent": "America"},
        {"id": "saint kitts and nevis", "name": "Saint Kitts and Nevis", "continent": "America"},
        {"id": "saint lucia", "name": "Saint Lucia", "continent": "America"},
        {"id": "saint vincent and the grenadines", "name": "Saint Vincent and the Grenadines", "continent": "America"},
        {"id": "suriname", "name": "Suriname", "continent": "America"},
        {"id": "trinidad and tobago", "name": "Trinidad and Tobago", "continent": "America"},
        {"id": "united states", "name": "United States", "continent": "America"},
        {"id": "uruguay", "name": "Uruguay", "continent": "America"},
        {"id": "venezuela", "name": "Venezuela", "continent": "America"},
        {"id": "afghanistan", "name": "Afghanistan", "continent": "Asia"},
        {"id": "armenia", "name": "Armenia", "continent": "Asia"},
        {"id": "azerbaijan", "name": "Azerbaijan", "continent": "Asia"},
        {"id": "bahrain", "name": "Bahrain", "continent": "Asia"},
        {"id": "bangladesh", "name": "Bangladesh", "continent": "Asia"},
        {"id": "bhutan", "name": "Bhutan", "continent": "Asia"},
        {"id": "brunei", "name": "Brunei", "continent": "Asia"},
        {"id": "cambodia", "name": "Cambodia", "continent": "Asia"},
        {"id": "china", "name": "China", "continent": "Asia"},
        {"id": "cyprus", "name": "Cyprus", "continent": "Asia"},
        {"id": "georgia", "name": "Georgia", "continent": "Asia"},
        {"id": "india", "name": "India", "continent": "Asia"},
        {"id": "indonesia", "name": "Indonesia", "continent": "Asia"},
        {"id": "iran", "name": "Iran", "continent": "Asia"},
        {"id": "iraq", "name": "Iraq", "continent": "Asia"},
        {"id": "israel", "name": "Israel", "continent": "Asia"},
        {"id": "japan", "name": "Japan", "continent": "Asia"},
        {"id": "jordan", "name": "Jordan", "continent": "Asia"},
        {"id": "kazakhstan", "name": "Kazakhstan", "continent": "Asia"},
        {"id": "kuwait", "name": "Kuwait", "continent": "Asia"},
        {"id": "kyrgyzstan", "name": "Kyrgyzstan", "continent": "Asia"},
        {"id": "laos", "name": "Laos", "continent": "Asia"},
        {"id": "lebanon", "name": "Lebanon", "continent": "Asia"},
        {"id": "malaysia", "name": "Malaysia", "continent": "Asia"},
        {"id": "maldives", "name": "Maldives", "continent": "Asia"},
        {"id": "mongolia", "name": "Mongolia", "continent": "Asia"},
        {"id": "myanmar", "name": "Myanmar", "continent": "Asia"},
        {"id": "nepal", "name": "Nepal", "continent": "Asia"},
        {"id": "north korea", "name": "North Korea", "continent": "Asia"},
        {"id": "oman", "name": "Oman", "continent": "Asia"},
        {"id": "pakistan", "name": "Pakistan", "continent": "Asia"},
        {"id": "palestine", "name": "Palestine", "continent": "Asia"},
        {"id": "philippines", "name": "Philippines", "continent": "Asia"},
        {"id": "qatar", "name": "Qatar", "continent": "Asia"},
        {"id": "saudi arabia", "name": "Saudi Arabia", "continent": "Asia"},
        {"id": "singapore", "name": "Singapore", "continent": "Asia"},
        {"id": "south korea", "name": "South Korea", "continent": "Asia"},
        {"id": "sri lanka", "name": "Sri Lanka", "continent": "Asia"},
        {"id": "syria", "name": "Syria", "continent": "Asia"},
        {"id": "taiwan", "name": "Taiwan", "continent": "Asia"},
        {"id": "tajikistan", "name": "Tajikistan", "continent": "Asia"},
        {"id": "thailand", "name": "Thailand", "continent": "Asia"},
        {"id": "timor-leste", "name": "Timor-Leste", "continent": "Asia"},
        {"id": "turkey", "name": "Turkey", "continent": "Asia"},
        {"id": "turkmenistan", "name": "Turkmenistan", "continent": "Asia"},
        {"id": "united arab emirates", "name": "United Arab Emirates", "continent": "Asia"},
        {"id": "uzbekistan", "name": "Uzbekistan", "continent": "Asia"},
        {"id": "vietnam", "name": "Vietnam", "continent": "Asia"},
        {"id": "yemen", "name": "Yemen", "continent": "Asia"},
        {"id": "albania", "name": "Albania", "continent": "Europe"},
        {"id": "andorra", "name": "Andorra", "continent": "Europe"},
        {"id": "austria", "name": "Austria", "continent": "Europe"},
        {"id": "belarus", "name": "Belarus", "continent": "Europe"},
        {"id": "belgium", "name": "Belgium", "continent": "Europe"},
        {"id": "bosnia and herzegovina", "name": "Bosnia and Herzegovina", "continent": "Europe"},
        {"id": "bulgaria", "name": "Bulgaria", "continent": "Europe"},
        {"id": "croatia", "name": "Croatia", "continent": "Europe"},
        {"id": "czech republic", "name": "Czech Republic", "continent": "Europe"},
        {"id": "denmark", "name": "Denmark", "continent": "Europe"},
        {"id": "estonia", "name": "Estonia", "continent": "Europe"},
        {"id": "finland", "name": "Finland", "continent": "Europe"},
        {"id": "france", "name": "France", "continent": "Europe"},
        {"id": "germany", "name": "Germany", "continent": "Europe"},
        {"id": "greece", "name": "Greece", "continent": "Europe"},
        {"id": "hungary", "name": "Hungary", "continent": "Europe"},
        {"id": "iceland", "name": "Iceland", "continent": "Europe"},
        {"id": "ireland", "name": "Ireland", "continent": "Europe"},
        {"id": "italy", "name": "Italy", "continent": "Europe"},
        {"id": "kosovo", "name": "Kosovo", "continent": "Europe"},
        {"id": "latvia", "name": "Latvia", "continent": "Europe"},
        {"id": "liechtenstein", "name": "Liechtenstein", "continent": "Europe"},
        {"id": "lithuania", "name": "Lithuania", "continent": "Europe"},
        {"id": "luxembourg", "name": "Luxembourg", "continent": "Europe"},
        {"id": "malta", "name": "Malta", "continent": "Europe"},
        {"id": "moldova", "name": "Moldova", "continent": "Europe"},
        {"id": "monaco", "name": "Monaco", "continent": "Europe"},
        {"id": "montenegro", "name": "Montenegro", "continent": "Europe"},
        {"id": "netherlands", "name": "Netherlands", "continent": "Europe"},
        {"id": "north macedonia", "name": "North Macedonia", "continent": "Europe"},
        {"id": "norway", "name": "Norway", "continent": "Europe"},
        {"id": "poland", "name": "Poland", "continent": "Europe"},
        {"id": "portugal", "name": "Portugal", "continent": "Europe"},
        {"id": "romania", "name": "Romania", "continent": "Europe"},
        {"id": "russia", "name": "Russia", "continent": "Europe"},
        {"id": "san marino", "name": "San Marino", "continent": "Europe"},
        {"id": "serbia", "name": "Serbia", "continent": "Europe"},
        {"id": "slovakia", "name": "Slovakia", "continent": "Europe"},
        {"id": "slovenia", "name": "Slovenia", "continent": "Europe"},
        {"id": "spain", "name": "Spain", "continent": "Europe"},
        {"id": "sweden", "name": "Sweden", "continent": "Europe"},
        {"id": "switzerland", "name": "Switzerland", "continent": "Europe"},
        {"id": "ukraine", "name": "Ukraine", "continent": "Europe"},
        {"id": "united kingdom", "name": "United Kingdom", "continent": "Europe"},
        {"id": "vatican city", "name": "Vatican City", "continent": "Europe"},
        {"id": "australia", "name": "Australia", "continent": "Oceania"},
        {"id": "fiji", "name": "Fiji", "continent": "Oceania"},
        {"id": "kiribati", "name": "Kiribati", "continent": "Oceania"},
        {"id": "marshall islands", "name": "Marshall Islands", "continent": "Oceania"},
        {"id": "micronesia", "name": "Micronesia", "continent": "Oceania"},
        {"id": "nauru", "name": "Nauru", "continent": "Oceania"},
        {"id": "new zealand", "name": "New Zealand", "continent": "Oceania"},
        {"id": "palau", "name": "Palau", "continent": "Oceania"},
        {"id": "papua new guinea", "name": "Papua New Guinea", "continent": "Oceania"},
        {"id": "samoa", "name": "Samoa", "continent": "Oceania"},
        {"id": "solomon islands", "name": "Solomon Islands", "continent": "Oceania"},
        {"id": "tonga", "name": "Tonga", "continent": "Oceania"},
        {"id": "tuvalu", "name": "Tuvalu", "continent": "Oceania"},
        {"id": "vanuatu", "name": "Vanuatu", "continent": "Oceania"},
    ]
    return jsonify(cultures), 200

@bp.route("/<culture_id>", methods=["GET"])
def get_culture(culture_id):

    id = culture_id.strip().lower()

    food_data = get_meals_by_country(id)
    country_data = get_countries(id)
    art_data = get_art_by_country(id)
    history_data = get_history(id)
    traditions_data = get_heritage_by_country(id)

    # Derive display name from country_data if available, else title-case the id
    if isinstance(country_data, dict) and country_data.get("name"):
        display_name = country_data["name"]
    else:
        display_name = id.replace("-", " ").title()

    return jsonify({
        "culture_id": culture_id,
        "name": display_name,
        "food": food_data,
        "country": country_data,
        "art": art_data,
        "history": history_data,
        "traditions": traditions_data
    }), 200